from typing import Protocol, TypeVar

from tlserver.config import TranslatorSettingsBase

ConfigT = TypeVar("ConfigT", bound=TranslatorSettingsBase)


class Translator(Protocol[ConfigT]):
    config: ConfigT

    @property
    def is_ready(self) -> bool: ...

    def pause(self) -> None: ...

    def resume(self) -> None: ...

    def activate(self) -> bool: ...

    async def translate(self, message: str) -> str: ...

    async def translate_batch(self, list_of_text_input: list[str]) -> list[str]: ...

    def check_if_language_available(self, language: str) -> bool: ...

    def change_output_language(self, output_language: str) -> str: ...

    def change_input_language(self, input_language: str) -> str: ...
